server:
  port: 8080
  servlet:
    context-path: /zhanghao
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bmw-first-springboot?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root
    password: '0206'
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zhanghao.first.model